#spring.datasource.url=jdbc:h2:mem:devopsdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#server.port=8086
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.application.name=devops
springdoc.swagger-ui.path=/swagger-ui.html
# ========================================
# H2 Database
# ========================================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ========================================
# JPA / Hibernate
# ========================================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========================================
# H2 Console
# ========================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ========================================
# Server
# ========================================
server.port=8086

